spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${JDBC_URL}