version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=local

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    
